# See https://www.dartlang.org/tools/pub/pubspec

name: playground
description: The playground mobile application.
version: 0.0.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  sliding_up_panel: ^0.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
